### ISSUE TITLE
What shall i do if i want change setting for svn?

### ISSUE THREAD

**Issue by weisiwu** [garethflowers/docker-svn-server#1]
hi, Gareth Flowers.
i'm a rookie to docker,and i have encounter a problem, by any chance ,could you help to have a look at question? i started a container by script as following:
``` shell
    docker run \
    --name svnserver \
    --detach \
    --volume /home/svn:/var/opt/svn \
    --publish 3690:3690 \
    garethflowers/svn-server
```
after start the container, i edited the config file: authz, passwd, svnserve.conf. to add a svn account. but how can i enable those new change in config files? i have try to restart the container, but it's inoprative.

**Comment by qq516249940** [comment]
> hi, Gareth Flowers.
> i'm a rookie to docker,and i have encounter a problem, by any chance ,could you help to have a look at question? i started a container by script as following:
> 
> ```shell
>     docker run \
>     --name svnserver \
>     --detach \
>     --volume /home/svn:/var/opt/svn \
>     --publish 3690:3690 \
>     garethflowers/svn-server
> ```
> 
> after start the container, i edited the config file: authz, passwd, svnserve.conf. to add a svn account. but how can i enable those new change in config files? i have try to restart the container, but it's inoprative.



hei，man！ you can look this https://blog.51cto.com/yanconggod/1927768

**Comment by garethflowers** [comment]
Closing this - assuming its resolved.

If not please feel free to post your docker logs for this container so we can see what error is being reported.
