### ISSUE TITLE
Where is subversion-tools?

### ISSUE THREAD

**Issue by AlexanderNaiden** [garethflowers/docker-svn-server#2]
Where is subversion-tools?

**Comment by garethflowers** [comment]
I'm not sure which "subversion-tools" you are referring to - could you explain a little?

Bear in mind this Docker image is for an SVN Server and contains no client side tools or binaries.

**Comment by AlexanderNaiden** [comment]
Sorry, it is not required for your docker image. I had mistaken. Subversion-tools  is used with Apache Subversion but your docker image configured to use only svn protocol. Subversion-tools contains usefull scripts especially hook scripts which I wanted to use. These tools allow developer to use scripts with post-commit hooks scripts. For example I use docker images of Subversion Server and Jenkins Server. So that during comitting into svn repopository Jenkins trigger job which runs rebuild of repopository.
